In [1]:
import pandas as pd

# Tabela A
municipio = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'nome': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'João Pessoa'],
    'uf': ['SP', 'RJ', 'MG', 'PB']})

# Tabela B
populacao = pd.DataFrame({
    'id': [1, 2, 4],
    'populacao': [12300000, 6748000, 817511]})

# Junção de tabelas usando merge
outer = pd.merge(municipio, populacao, on='id', how='outer')
inner = pd.merge(municipio, populacao, on='id', how='inner')
left = pd.merge(municipio, populacao, on='id', how='left')
right = pd.merge(municipio, populacao, on='id', how='right')

print(f"Junção externa (outer join): {len(outer)} registros")
print(f"Junção interna (inner join): {len(inner)} registros")
print(f"Junção à esquerda (left join): {len(left)} registros")
print(f"Junção à direita (right join): {len(right)} registros")

Junção externa (outer join): 4 registros
Junção interna (inner join): 3 registros
Junção à esquerda (left join): 4 registros
Junção à direita (right join): 3 registros

In [2]:
file = '~/Downloads/dados/divulgacao_anos_iniciais_municipios_2023/divulgacao_anos_iniciais_municipios_2023.xlsx'
ideb = pd.read_excel(file, skiprows=9, na_values=['-', 'ND', 'N/A', 'N/D', 'N/A', 'ND/NA', 'ND/N/A'])

list(ideb.columns)
selecao_colunas = ['SG_UF', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'REDE',
                   'VL_OBSERVADO_2005', 'VL_OBSERVADO_2007', 'VL_OBSERVADO_2009','VL_OBSERVADO_2011', 'VL_OBSERVADO_2013', 'VL_OBSERVADO_2015', 'VL_OBSERVADO_2017', 'VL_OBSERVADO_2019', 'VL_OBSERVADO_2021', 'VL_OBSERVADO_2023']

ideb = ideb[selecao_colunas]

print("Antes da transformação:")
display(ideb.head())

ideb.info()

# Transformando a tabela de formato largo para formato longo
ideb = (
    ideb.melt(id_vars=['SG_UF', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'REDE'],
          value_vars=['VL_OBSERVADO_2005', 'VL_OBSERVADO_2007', 'VL_OBSERVADO_2009','VL_OBSERVADO_2011', 'VL_OBSERVADO_2013', 'VL_OBSERVADO_2015', 'VL_OBSERVADO_2017', 'VL_OBSERVADO_2019', 'VL_OBSERVADO_2021', 'VL_OBSERVADO_2023'],
          var_name='ano', value_name='ideb'
          )
          .assign(ano=lambda x: x['ano'].str.replace('VL_OBSERVADO_', '').astype(int))
          .rename(columns=lambda x: x.lower())
)

print("Depois da transformação:")
display(ideb.head())

Antes da transformação:

,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,REDE,VL_OBSERVADO_2005,VL_OBSERVADO_2007,VL_OBSERVADO_2009,VL_OBSERVADO_2011,VL_OBSERVADO_2013,VL_OBSERVADO_2015,VL_OBSERVADO_2017,VL_OBSERVADO_2019,VL_OBSERVADO_2021,VL_OBSERVADO_2023
0,RO,1100015.0,Alta Floresta D'Oeste,Estadual,3.5,3.9,4.3,4.2,5.3,5.8,6.2,5.8,4.6,5.9
1,RO,1100015.0,Alta Floresta D'Oeste,Municipal,NaN,NaN,NaN,NaN,NaN,5.0,5.1,4.7,4.8,5.1
2,RO,1100015.0,Alta Floresta D'Oeste,Pública,3.7,4.0,4.5,4.3,5.4,5.8,6.2,5.7,4.8,5.3
3,RO,1100023.0,Ariquemes,Estadual,4.0,4.3,4.9,4.9,5.2,5.6,6.0,5.3,5.8,6.1
4,RO,1100023.0,Ariquemes,Municipal,3.5,3.7,4.2,4.4,4.8,5.0,5.4,5.1,4.5,5.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14514 entries, 0 to 14513
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   SG_UF              14513 non-null  object
 1   CO_MUNICIPIO       14497 non-null  float64
 2   NO_MUNICIPIO       14497 non-null  object
 3   REDE               14497 non-null  object
 4   VL_OBSERVADO_2005  12083 non-null  float64
 5   VL_OBSERVADO_2007  13549 non-null  float64
 6   VL_OBSERVADO_2009  13069 non-null  float64
 7   VL_OBSERVADO_2011  12634 non-null  float64
 8   VL_OBSERVADO_2013  12287 non-null  float64
 9   VL_OBSERVADO_2015  12048 non-null  float64
 10  VL_OBSERVADO_2017  12511 non-null  float64
 11  VL_OBSERVADO_2019  12188 non-null  float64
 12  VL_OBSERVADO_2021  11181 non-null  float64
 13  VL_OBSERVADO_2023  11875 non-null  float64
dtypes: float64(11), object(3)
memory usage: 1.6+ MB
Depois da transformação:

  sg_uf  co_municipio           no_municipio       rede   ano  ideb
0    RO     1100015.0  Alta Floresta D'Oeste   Estadual  2005   3.5
1    RO     1100015.0  Alta Floresta D'Oeste  Municipal  2005   NaN
2    RO     1100015.0  Alta Floresta D'Oeste    Pública  2005   3.7
3    RO     1100023.0              Ariquemes   Estadual  2005   4.0
4    RO     1100023.0              Ariquemes  Municipal  2005   3.5

## Formato de Dados

- WIDE: os dados se expandem em colunas
- LONG: os dados se expandem em linhas (Do ponto de vista estatístico, o LONG seria a melhor escolha)

In [12]:
from unidecode import unidecode
# DTB
file = '~/Downloads/dados/DTB_2025/RELATORIO_DTB_BRASIL_2025_MUNICIPIOS.xls'
dtb = pd.read_excel(file, skiprows=6)

# Normalização dos nomes das colunas
dtb.rename(columns=lambda x: unidecode(x.strip().lower()
                                       .replace(' ', '_')
                                       .replace('nome_', 'no_')
                                       .replace('codigo_', 'co_')), inplace=True)

dtb = dtb.rename(columns={'codigo_municipio_completo': 'co_municipio'})
dtb.columns

Index(['uf', 'no_uf', 'regiao_geografica_intermediaria',
       'no_regiao_geografica_intermediaria', 'regiao_geografica_imediata',
       'no_regiao_geografica_imediata', 'municipio', 'co_municipio',
       'no_municipio'],
      dtype='object')

In [13]:
dtb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5571 entries, 0 to 5570
Data columns (total 9 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   uf                                  5571 non-null   int64
 1   no_uf                               5571 non-null   object
 2   regiao_geografica_intermediaria     5571 non-null   int64
 3   no_regiao_geografica_intermediaria  5571 non-null   object
 4   regiao_geografica_imediata          5571 non-null   int64
 5   no_regiao_geografica_imediata       5571 non-null   object
 6   municipio                           5571 non-null   int64
 7   co_municipio                        5571 non-null   int64
 8   no_municipio                        5571 non-null   object
dtypes: int64(5), object(4)
memory usage: 391.8+ KB

In [ ]:
# Sociais
variaveis = ['ANO', 'CODMUN7', 'PPOB', 'T_ANALF18M', 'GINI',
             'RDPC', 'IDHM', 'POP']
file = '~/Downloads/dados/censo_total_1991_2010.xlsx'
atlas = (pd.read_excel(file, sheet_name=1)
         .rename(columns=lambda x: x.upper())
         [variaveis])

        ANO  CODMUN7   PPOB  T_ANALF18M  GINI     RDPC   IDHM      POP
0      1991  1100015  83.15       25.71  0.63   198.46  0.329    23417
1      1991  1100023  65.78       18.37  0.57   319.47  0.432    56061
2      1991  1100031  88.55       27.10  0.70   116.38  0.309     7601
3      1991  1100049  73.35       23.29  0.66   320.24  0.407    69173
4      1991  1100056  76.15       22.29  0.60   240.10  0.386    19451
...     ...      ...    ...         ...   ...      ...    ...      ...
16690  2010  5222005  23.73        8.52  0.46   664.33  0.712    12501
16691  2010  5222054  23.14       13.51  0.46   651.07  0.684     7288
16692  2010  5222203  52.51       17.07  0.48   376.72  0.647     4685
16693  2010  5222302  45.09       20.75  0.47   401.84  0.634     4739
16694  2010  5300108  16.00        3.66  0.63  1715.11  0.824  2543802

[16695 rows x 8 columns]

In [24]:
# Padronizar o nome das colunas
atlas.rename(columns={'CODMUN7': 'co_municipio'}, inplace=True)
atlas.rename(columns=lambda x: x.lower(), inplace=True)
atlas.ano.value_counts()

ano
1991    5565
2000    5565
2010    5565
Name: count, dtype: int64

In [32]:
print("Ideb", ideb.shape)
print("DTB", dtb.shape)

ideb_r = ideb.drop(columns=['sg_uf', 'no_municipio'])
atlas_r = atlas.query('ano == 2010').drop(columns=['ano'])

df = (
    dtb
    .assign(co_regiao = lambda x: x.co_municipio.astype(str).str[:1].astype(int),
            no_regiao = lambda x: x.co_regiao.map({1: 'Norte', 2: 'Nordeste', 3: 'Sudeste', 4: 'Sul', 5: 'Centro-Oeste'}))
    .merge(ideb_r, on='co_municipio', how='inner', validate='1:m')
    .merge(atlas_r, on='co_municipio', how='left')
)
print("DF", df.shape)
df

Ideb (145140, 6)
DTB (5571, 9)
DF (144970, 20)

,uf,no_uf,regiao_geografica_intermediaria,no_regiao_geografica_intermediaria,regiao_geografica_imediata,no_regiao_geografica_imediata,municipio,co_municipio,no_municipio,co_regiao,no_regiao,rede,ano,ideb,ppob,t_analf18m,gini,rdpc,idhm,pop
0,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,1,Norte,Estadual,2005,3.5,47.12,13.00,0.58,476.99,0.641,24097.0
1,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,1,Norte,Municipal,2005,NaN,47.12,13.00,0.58,476.99,0.641,24097.0
2,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,1,Norte,Pública,2005,3.7,47.12,13.00,0.58,476.99,0.641,24097.0
3,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,1,Norte,Estadual,2007,3.9,47.12,13.00,0.58,476.99,0.641,24097.0
4,11,Rondônia,1102,Ji-Paraná,110005,Cacoal,15,1100015,Alta Floresta D'Oeste,1,Norte,Municipal,2007,NaN,47.12,13.00,0.58,476.99,0.641,24097.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144965,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,5,Centro-Oeste,Pública,2019,6.1,16.00,3.66,0.63,1715.11,0.824,2543802.0
144966,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,5,Centro-Oeste,Estadual,2021,5.9,16.00,3.66,0.63,1715.11,0.824,2543802.0
144967,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,5,Centro-Oeste,Pública,2021,5.9,16.00,3.66,0.63,1715.11,0.824,2543802.0
144968,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,5,Centro-Oeste,Estadual,2023,5.9,16.00,3.66,0.63,1715.11,0.824,2543802.0
144969,53,Distrito Federal,5301,Distrito Federal,530001,Distrito Federal,108,5300108,Brasília,5,Centro-Oeste,Pública,2023,5.9,16.00,3.66,0.63,1715.11,0.824,2543802.0